### ISSUE TITLE
Updating d0x libraries to shadow-cljs and/or Web3.js 1.7(cljs-web3-next)

### ISSUE THREAD

**Issue by madis** [district0x/d0x-INFRA#22]
- [X] [com.github.district0x/re-frame-web3-fx](https://github.com/district0x/re-frame-web3-fx)
- [X] [district0x/cljs-solidity-sha3](https://github.com/district0x/cljs-solidity-sha3)
- [X] [district0x/district-parsers](https://github.com/district0x/district-parsers)  (madis)
- [X] [district0x/district-server-db](https://github.com/district0x/district-server-db)  (madis)
- [X] [district0x/district-server-smart-contracts](https://github.com/district0x/district-server-smart-contracts) (madis)
- [X] [district0x/district-server-web3](https://github.com/district0x/district-server-web3)
- [X] [district0x/district-server-web3-events](https://github.com/district0x/district-server-web3-events) (madis)
- [x] [district0x/district-server-web3-watcher](https://github.com/district0x/district-server-web3-watcher) (madis)
- [X] [district0x/district-ui-smart-contracts](https://github.com/district0x/district-ui-smart-contracts)
- [X] [district0x/district-ui-web3](https://github.com/district0x/district-ui-web3)
- [X] [district0x/district-ui-web3-accounts](https://github.com/district0x/district-ui-web3-accounts)
- [X] [district0x/district-ui-web3-balances](https://github.com/district0x/district-ui-web3-balances)
- [X] [district0x/district-ui-web3-sync-now](https://github.com/district0x/district-ui-web3-sync-now)
- [X] [district0x/district-ui-web3-tx](https://github.com/district0x/district-ui-web3-tx)
- [X] [district0x/district-ui-web3-tx-costs](https://github.com/district0x/district-ui-web3-tx-costs)
- [X] [district0x/district-ui-web3-tx-id](https://github.com/district0x/district-ui-web3-tx-id)
- [x] [district0x/district-validation](https://github.com/district0x/district-validation)
- [X] [district0x/district-web3-utils](https://github.com/district0x/district-web3-utils)
- [X] [district0x/eip55](https://github.com/district0x/eip55)
- [X] [io.github.district0x/district-ui-web3-chain](https://github.com/district0x/district-ui-web3-chain)

Indirect dependents

- [x] [district0x/district-ui-component-active-account](https://github.com/district0x/district-ui-component-active-account)
- [x] [district0x/district-ui-web3-account-balances](https://github.com/district0x/district-ui-web3-account-balances) (madis)
- [x] [district0x/district-ui-component-active-account-balance](https://github.com/district0x/district-ui-component-active-account-balance) (madis)
- [x] [district0x/district-ui-component-tx-button](https://github.com/district0x/district-ui-component-tx-button) (madis)
- [x] [district0x/district-ui-web3-tx-log-core](https://github.com/district0x/district-ui-web3-tx-log-core) (madis)
- [x] [district0x/district-ui-web3-tx-log](https://github.com/district0x/district-ui-web3-tx-log) (madis)

More
- [X] [district0x/cljs-ipfs-http-client](https://github.com/district0x/cljs-ipfs-http-client) (madis)
- [x] [district0x/re-frame-ipfs-fx](https://github.com/district0x/re-frame-ipfs-fx) (madis)

**Comment by madis** [comment]
![image](https://user-images.githubusercontent.com/674621/187473355-9f2add42-a4aa-41b2-bc3e-e6853056c1f7.png)

**Comment by madvas** [comment]
![image](https://user-images.githubusercontent.com/3857155/187681632-aa2b0c41-9994-4bd2-8ad6-f5029270e9bf.png)
