### ISSUE TITLE
Create wrapper for 0xConnect library

### ISSUE THREAD

**Issue by madvas** [district0x/d0x-INFRA#5]
Create wrapper library for easier working with [0xConnect](https://0xproject.com/docs/connect), similar to [cljs-web3](https://github.com/district0x/cljs-web3/).
Let's call it `cljs-0x-connect`. 

This lib should mainly do: 
* Split library into namespaces: `cljs-0x-connect.http-client` and `cljs-0x-connect.ws-orderbook`
* Do `clj->js` + camelCase on arguments passed into a functions. Same way as cljs-web3. 
* Do `js->clj` + kebab-case on responses returned from functions. Same way as cljs-web3.  Note, function should still return native JS promise as it originally is, just value passed to that promise should be converted. 
* Contain convenience fns: `cljs-0x-connect.http-client/create-http-client` and `cljs-0x-connect.ws-orderbook/create-ws-orderbook-channel` which are equivalents to `new HttpClient` and `new WebSocketOrderbookChannel`. 

For invoking functions `js-invoke` should be used instead of using JS interop, so we avoid eternal problems with externs. 

In order to this lib to work, you'll likely need to create `cljsjs/0x-connect` library. Alternative option would be to try to use new `:npm-deps`. It would be better, because of dead code elimination, but not sure if it's gonna work. You can give it a try. 

Library should be usable in both, nodejs and browser. 

As for documentation, you don't need to document every single function, since it's just a wrapper, just write something similar to `cljs-web3` readme. 

As for tests, no need to test every single function, just a few random, so we know cljs<->js conversions work. You'll need to somehow mock responses from server. If you want to try out this lib on live server, try [RadarRelay](https://app.radarrelay.com), their API should be compliant with 0xConnect.

**Comment by fbielejec** [comment]
Closed with: https://github.com/district0x/cljs-0x-connect
