### ISSUE TITLE
Create re-frame effects for 0xConnect library

### ISSUE THREAD

**Issue by madvas** [district0x/d0x-INFRA#6]
After https://github.com/district0x/d0x-INFRA/issues/5 is done, create re-frame effects for working with [0xConnect](https://0xproject.com/docs/connect), using previously created wrapper `cljs-0x-connect` similar to [re-frame-web3-fx](https://github.com/district0x/re-frame-web3-fx). 
Let's call it `re-frame-0x-connect-fx`.

Library effects should have following pattern:
```clojure
(reg-event-fx
    ::my-event
    (fn []
      {:0x-connect [{:http-client http-client
                     :fn :get-fees
                     :args [{:exchange-token-address "0x123"}]
                     :on-success [::on-success]
                     :on-error [::on-error]}
                    {:ws-orderbook-channel ws-chan
                     :fn :subscribe
                     :args [{:base-token-address "0x123"}]
                     :on-close [::on-close]
                     :on-error [::on-error]
                     :on-snapshot [::on-snapshot]
                     :on-update [::on-update]}
                    {:ws-orderbook-channel ws-chan
                     :fn :close}]}))
```

This lib should be fully documented in repo's README. 
This lib should be fully tested, with tests runnable with travis.

**Comment by fbielejec** [comment]
WIP: https://github.com/district0x/project-0x-connect-fx. We decided it's not needed anymore. Close?
