### ISSUE TITLE
Create district-ui-web3-sync-now module

### ISSUE THREAD

**Issue by madvas** [district0x/d0x-INFRA#7]
After implementing https://github.com/district0x/district-ui-now/issues/1, create simple module `district-ui-web3-sync-now` module, that fetches current time from blockchain after event `:district.ui.web3.events/web3-created` and sets it as now to `district-ui-now` module. 

To get current time use this: 
This is node.js snippet, you should use it in form of re-frame effects of course
```clojure
(district-web3-utils/web3-time->date-time (:timestamp (web3-eth/get-block @web3 (web3-eth/block-number @web3))))
```

It's not ideal, since it's last block's time, not current time, but I think it will serve the purpose. I don't know of other way to get current time except having contract that returns Solidity's `now`. 

This module should also provide event `::inc-now`, that increments both: ganache's time using `web3-evm/increment-time` and `:district-ui-now/inc-now` for convenient incrementing via REPL during runtime.  

No config options need to be passed into this module.

**Comment by fbielejec** [comment]
Closed with https://github.com/district0x/district-ui-web3-sync-now
