### ISSUE TITLE
meta-tags ui component

### ISSUE THREAD

**Issue by madvas** [district0x/d0x-INFRA#8]
Create simple repo for `district.ui.component.meta-tags`, which is using same underlying cljsjs lib as NameBazaar. 

API should be like: 
```clojure
[meta-tags {:title "Page Title" :description "Page Desc"}]
```
These props will add `[:title {:id "title"} title]` and `[:meta {:id "description" :name "description" :content description}]`

Optionally you can pass children for more meta tags
```clojure
[meta-tags {:title "Page Title" :description "Page Desc"}
  [:meta {:id "some-other-meta" :name "some-other-meta" :content blah}]]
```

**Comment by fbielejec** [comment]
Closed: https://github.com/district0x/district-ui-component-meta-tags
